alertmanager:
  enabled: false

grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      isDefault: false
    - name: Tempo
      type: tempo
      url: http://tempo:3100
      access: proxy
      isDefault: false

