# Copyright (c) 2025 Juan Estevez Castillo
# Licensed under AGPL v3. Commercial licenses available.
# See LICENSE or https://www.gnu.org/licenses/agpl-3.0.html
"""
HTML Report Generator for Heimr.
Generates standalone HTML reports with interactive Plotly charts.
"""
import markdown
from datetime import datetime


class HTMLReportGenerator:
    """Generate standalone HTML reports from Markdown content."""
    
    HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Heimr Performance Analysis Report</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        :root {{
            --bg-primary: #0F172A;
            --bg-secondary: #1E293B;
            --text-primary: #E2E8F0;
            --text-secondary: #94A3B8;
            --accent-cyan: #00D4AA;
            --accent-purple: #7C3AED;
            --success: #22C55E;
            --warning: #F59E0B;
            --danger: #EF4444;
        }}
        
        * {{ box-sizing: border-box; }}
        
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            line-height: 1.6;
            margin: 0;
            padding: 40px;
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        
        h1 {{
            font-size: 2rem;
            margin-bottom: 1rem;
            color: var(--accent-cyan);
        }}
        
        h2 {{
            font-size: 1.5rem;
            margin-top: 2rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid var(--bg-secondary);
        }}
        
        h3 {{
            font-size: 1.2rem;
            color: var(--text-secondary);
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            background: var(--bg-secondary);
            border-radius: 8px;
            overflow: hidden;
        }}
        
        th {{
            background: var(--accent-purple);
            color: white;
            padding: 12px;
            text-align: left;
        }}
        
        td {{
            padding: 10px 12px;
            border-bottom: 1px solid var(--bg-primary);
        }}
        
        tr:hover {{
            background: rgba(0, 212, 170, 0.1);
        }}
        
        code {{
            background: var(--bg-secondary);
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 0.9em;
        }}
        
        blockquote {{
            border-left: 4px solid var(--accent-cyan);
            margin: 1rem 0;
            padding: 0.5rem 1rem;
            background: rgba(0, 212, 170, 0.1);
            border-radius: 0 8px 8px 0;
        }}
        
        hr {{
            border: none;
            border-top: 2px solid var(--bg-secondary);
            margin: 2rem 0;
        }}
        
        .status-banner {{
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }}
        
        .status-ok {{ border-left: 4px solid var(--success); background: rgba(34, 197, 94, 0.1); }}
        .status-warning {{ border-left: 4px solid var(--warning); background: rgba(245, 158, 11, 0.1); }}
        .status-failed {{ border-left: 4px solid var(--danger); background: rgba(239, 68, 68, 0.1); }}
        
        /* Print styles */
        @media print {{
            body {{
                background: white;
                color: #333;
                padding: 20px;
            }}
            
            .container {{
                max-width: 100%;
            }}
            
            h1, h2 {{
                color: #333;
            }}
            
            table {{
                background: #f5f5f5;
            }}
            
            .js-plotly-plot {{
                page-break-inside: avoid;
            }}
        }}
        
        .footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid var(--bg-secondary);
            text-align: center;
            color: var(--text-secondary);
            font-size: 0.9rem;
        }}
    </style>
</head>
<body>
    <div class="container">
        {content}
        <div class="footer">
            Generated by <strong>Heimr.ai</strong> on {timestamp}<br>
            <em>Print this page (Ctrl+P) to save as PDF</em>
        </div>
    </div>
</body>
</html>'''

    def __init__(self):
        """Initialize HTML generator."""
        self.md = markdown.Markdown(extensions=[
            'tables',
            'fenced_code',
            'codehilite',
            'nl2br',
            'sane_lists',
            'md_in_html'  # Allow HTML passthrough
        ])
    
    def generate_html(self, markdown_content: str, output_path: str):
        """
        Convert markdown content to standalone HTML.
        
        Args:
            markdown_content: Markdown text with embedded Plotly HTML
            output_path: Path to save the HTML file
        """
        # Convert markdown to HTML (Plotly HTML passes through)
        html_content = self.md.convert(markdown_content)
        
        # Wrap in template
        full_html = self.HTML_TEMPLATE.format(
            content=html_content,
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        )
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(full_html)
    
    def generate_from_file(self, markdown_file: str, output_path: str):
        """
        Convert markdown file to HTML.
        
        Args:
            markdown_file: Path to markdown file
            output_path: Path to save the HTML file
        """
        with open(markdown_file, 'r', encoding='utf-8') as f:
            markdown_content = f.read()
        
        self.generate_html(markdown_content, output_path)
