import yaml
import os
from datetime import datetime

# Define section titles based on ID prefixes
PREFIX_MAP = {
    "API": "API & Web Services",
    "SVC": "Microservices & Distributed Patterns",
    "MSG": "Event-Driven & Streaming (Kafka/RabbitMQ)",
    "CSH": "Caching Layer (Redis/Memcached)",
    "DB": "Database & Storage (SQL/NoSQL)",
    "INF": "Infrastructure & Kubernetes",
    "SRV": "Serverless (FaaS)",
    "GPU": "AI/ML Inference (Specialized)",
    "SEC": "Security & Edge",
    "LB": "Load Balancer & Reverse Proxy",
    "NET": "Network Layer (Lower Level)",
    "STO": "Storage & Volume",
    "RES": "Resource Exhaustion (Granular)",
    "OBS": "Observability & Monitoring",
    "CFG": "Configuration & Deployment",
    "CLD": "Cloud Provider & Control Plane",
    "CTR": "Container Runtime & Sidecars",
    "PKI": "Certificate & PKI",
    "ASC": "Autoscaling & Operators",
    "OBJ": "Object Storage",
    "CDN": "CDN & Edge Computing",
    "TSDB": "Time-Series Databases",
    "POOL": "Connection Poolers & Queues",
    "EBPF": "eBPF & Kernel-Level",
    "TRC": "Distributed Tracing",
    "GITOPS": "GitOps & Chaos Engineering",
    "MTN": "Multi-Tenancy Isolation",
    "CDC": "Data Pipeline & CDC"
}

# Define order of sections
SECTION_ORDER = [
    "API", "SVC", "MSG", "CSH", "DB", "INF", "SRV", "GPU", "SEC",
    "LB", "NET", "STO", "RES", "OBS", "CFG", "CLD", "CTR", "PKI",
    "ASC", "OBJ", "CDN", "TSDB", "POOL", "EBPF", "TRC", "GITOPS",
    "MTN", "CDC"
]

def generate_markdown(yaml_path, output_path):
    if not os.path.exists(yaml_path):
        print(f"Error: {yaml_path} not found")
        return

    with open(yaml_path, 'r') as f:
        scenarios = yaml.safe_load(f)

    # Group scenarios by prefix
    grouped = {prefix: [] for prefix in SECTION_ORDER}
    for scenario in scenarios:
        prefix = scenario['id'].split('-')[0]
        if prefix in grouped:
            grouped[prefix].append(scenario)
        else:
            print(f"Warning: Unknown prefix {prefix} for ID {scenario['id']}")

    # Generate Markdown
    with open(output_path, 'w') as f:
        f.write(f"<!-- \nDO NOT EDIT THIS FILE DIRECTLY.\nThis file is auto-generated from {yaml_path}.\nRun `python3 scripts/generate_failure_docs.py` to update.\nGenerated at: {datetime.now().isoformat()}\n-->\n\n")
        f.write("# Comprehensive Failure Scenarios Catalog\n\n")
        f.write("This document serves as a master catalog of failure scenarios for generating training data. It covers various architectural patterns, system layers, and common failure modes found in modern distributed systems.\n\n")

        for i, prefix in enumerate(SECTION_ORDER, 1):
            if not grouped[prefix]:
                continue
                
            title = PREFIX_MAP.get(prefix, prefix)
            f.write(f"## {i}. {title}\n\n")
            
            # Add section description (optional, hardcoded for now or could be in YAML)
            # For simplicity, skipping per-section description unless we add it to YAML metadata
            
            f.write("| ID | Name | Description | Metrics Pattern | Root Cause |\n")
            f.write("| :--- | :--- | :--- | :--- | :--- |\n")
            
            for s in grouped[prefix]:
                # Escape pipes in content just in case
                name = f"**{s['name']}**"
                desc = s['description'].replace('|', '\\|')
                metrics = s['metrics_pattern'].replace('|', '\\|')
                root = s['root_cause'].replace('|', '\\|')
                
                f.write(f"| `{s['id']}` | {name} | {desc} | {metrics} | {root} |\n")
            
            f.write("\n")

    print(f"Successfully generated {output_path} from {yaml_path}")

if __name__ == "__main__":
    generate_markdown('FAILURE_SCENARIOS.yaml', 'docs/FAILURE_SCENARIOS.md')
