apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-generator-sa
  namespace: heimr-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-generator-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "configmaps"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["heimr.ai"]
    resources: ["chaosscenarios"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-generator-binding
subjects:
  - kind: ServiceAccount
    name: data-generator-sa
    namespace: heimr-core
roleRef:
  kind: ClusterRole
  name: data-generator-role
  apiGroup: rbac.authorization.k8s.io
