import os
import sys


class GitHubReporter:
    """
    Generates a GitHub Actions Step Summary.
    See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
    """

    def __init__(self, output_path: str = None):
        # Default to GITHUB_STEP_SUMMARY env var if no path provided
        self.output_path = output_path or os.getenv("GITHUB_STEP_SUMMARY")

    def generate_summary(self, stats: dict, anomalies: dict, failure_reasons: list = None, tags: dict = None):
        """
        Generate and append the summary to the step summary file.
        """
        if not self.output_path:
            return

        failed = len(failure_reasons) > 0 if failure_reasons else False
        status_icon = "❌" if failed else "✅"
        status_text = "Failed" if failed else "Passed"

        summary = []
        summary.append(f"# {status_icon} Heimr Load Test Analysis: {status_text}")

        if failed:
            summary.append("### 🚨 Failure Reasons")
            for reason in failure_reasons:
                summary.append(f"- {reason}")
            summary.append("")

        # Context Table
        if tags:
            summary.append("### 🏷️ Build Context")
            summary.append("| Key | Value |")
            summary.append("|---|---|")
            for k, v in tags.items():
                summary.append(f"| **{k}** | `{v}` |")
            summary.append("")

        # Metrics Table (Level 1)
        summary.append("### 📊 Primary KPIs (Level 1)")
        summary.append("| Metric | Value | Threshold | Status |")
        summary.append("|---|---|---|---|")

        # Helper to format rows
        def row(name, value, unit=""):
            return f"| {name} | **{value}** {unit} | - | - |"

        summary.append(f"| P95 Latency | {stats.get('p95_latency', 0):.2f} | ms | |")
        summary.append(f"| Error Rate | {stats.get('error_rate', 0):.2f} | % | |")
        summary.append(f"| Throughput | {stats.get('throughput', 0):.2f} | req/s | |")
        summary.append(f"| P50 Latency | {stats.get('p50_latency', 0):.2f} | ms | |")
        summary.append(f"| P99 Latency | {stats.get('p99_latency', 0):.2f} | ms | |")

        if anomalies['count'] > 0:
            summary.append(f"| **Anomalies** | 🔴 **{anomalies['count']}** | 0 | ❌ |")
        else:
            summary.append("| Anomalies | 0 | 0 | ✅ |")

        summary.append("")

        # Link to artifacts (if applicable, though usually artifacts are separate)
        summary.append("> *Report generated by [Heimr](https://github.com/jdestevezcastillo-perfeng/Heimr.ai)*")
        summary.append("")

        # Write to file (append mode is standard for step summary)
        try:
            with open(self.output_path, "a", encoding="utf-8") as f:
                f.write("\n".join(summary))
        except Exception as e:
            print(f"Warning: Failed to write GitHub Summary: {e}", file=sys.stderr)
