apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosscenarios.heimr.ai
spec:
  group: heimr.ai
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                action:
                  type: string
                target:
                  type: object
                  properties:
                    labelSelector:
                      type: string
                config:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                duration:
                  type: string
  scope: Namespaced
  names:
    plural: chaosscenarios
    singular: chaosscenario
    kind: ChaosScenario
    shortNames:
    - chaos
