apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-controller
  namespace: heimr-chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-controller
  template:
    metadata:
      labels:
        app: chaos-controller
    spec:
      serviceAccountName: chaos-controller-sa
      containers:
        - name: controller
          image: asia-northeast1-docker.pkg.dev/tokyo-snow-479722-a2/heimr/chaos-controller:instrumented
          imagePullPolicy: Always
          env:
            - name: KOPF_VERBOSE
              value: "1"
