{{- range .Values.databases }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    type: sim-db-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        type: sim-db-agent
    spec:
      containers:
        # Main DB Container
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
        
        # Chaos Sidecar Agent
        - name: chaos-agent
          image: "{{ $.Values.global.imageRegistry }}/sim-db-agent:latest"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          env:
            - name: DB_HOST
              value: "localhost"
            - name: DB_PASS
              value: "postgres"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: chaos-api
      port: 8000
      targetPort: 8000
{{- end }}
