apiVersion: v1
kind: Service
metadata:
  name: error-generator
  namespace: heimr-chaos
  labels:
    app: error-generator
    component: chaos-generator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: error-generator
